import type { Patient } from './types';

export const patients: Patient[] = [
  {
    id: 1,
    name: 'Patient 1',
    age: 65,
    sex: 'male',
    conditions: ['t2dm'],
    allergies: ['penicillin'],
    medications: ['Metformin', 'Glimepiride', 'Telmisartan', 'Atorvastatin'],
    labs: {
      creatinine: 2.1,
      egfr: 31.2,
      hba1c: 8.4,
      k: 5.1,
      troponin: 4.8,
      bp: '90/60',
      hr: 110,
      spo2: 94,
    },
    summary: '65M with type 2 diabetes, CKD stage 3b, penicillin anaphylaxis.',
  },
  {
    id: 2,
    name: 'Patient 2',
    age: 58,
    sex: 'female',
    conditions: [],
    allergies: [],
    medications: ['Enoxaparin', 'Paracetamol', 'Tramadol', 'Pantoprazole'],
    labs: {
      creatinine: 0.9,
      egfr: 82,
      hgb: 10.2,
    },
    summary: '58F with pain control needs and mild anemia.',
  },
  {
    id: 3,
    name: 'Patient 3',
    age: 78,
    sex: 'male',
    conditions: ['ckd', 'hpn'],
    allergies: ['sulfonamide'],
    medications: ['Amlodipine', 'Telmisartan', 'Metformin', 'Glimepiride', 'Atorvastatin', 'Aspirin', 'Pantoprazole', 'Escitalopram', 'Tamsulosin', 'Paracetamol', 'Diclofenac', 'Calcium+D3'],
    labs: {
      creatinine: 1.4,
      egfr: 48,
      k: 4.8,
    },
    summary: '78M with polypharmacy, sulfonamide rash history, CKD stage 3a.',
  },
  {
    id: 4,
    name: 'Patient 4',
    age: 6,
    sex: 'male',
    weightKg: 20,
    conditions: ['epilepsy'],
    allergies: [],
    medications: ['Sodium Valproate', 'Levetiracetam'],
    labs: {
      valproate_level: 85,
    },
    summary: '6yo child with epilepsy on valproate and levetiracetam.',
  },
  {
    id: 5,
    name: 'Patient 5',
    age: 62,
    sex: 'male',
    conditions: ['hf'],
    allergies: ['ace inhibitor'],
    medications: ['Furosemide', 'Carvedilol', 'Amlodipine', 'Erythropoietin', 'Calcium'],
    labs: {
      creatinine: 4.8,
      egfr: 12,
      k: 5.6,
    },
    summary: '62M with heart failure, advanced CKD, ACE inhibitor angioedema.',
  },
  {
    id: 6,
    name: 'Patient 6',
    age: 28,
    sex: 'female',
    conditions: ['pregnancy'],
    allergies: ['codeine'],
    medications: ['Methyldopa', 'Folic acid', 'Iron'],
    labs: {
      creatinine: 0.6,
      hgb: 10.8,
    },
    summary: '28F at 32 weeks pregnant with hypertension and codeine allergy.',
  },
  {
    id: 7,
    name: 'Patient 7',
    age: 35,
    sex: 'female',
    conditions: ['icu'],
    allergies: ['penicillin'],
    medications: ['Meropenem', 'Noradrenaline', 'Insulin infusion', 'Enoxaparin', 'Pantoprazole'],
    labs: {
      creatinine: 3.2,
      egfr: 18,
      wbc: 22,
      lactate: 4.8,
      hr: 118,
      bp: '85/50',
      spo2: 92,
      rr: 28,
      temp: 39.2,
    },
    summary: '35F ICU patient with acute kidney injury and penicillin rash history.',
  },
  {
    id: 8,
    name: 'Patient 8',
    age: 68,
    sex: 'male',
    conditions: ['af', 'hf', 'htn', 't2dm', 'tia'],
    allergies: [],
    medications: ['Warfarin', 'Bisoprolol', 'Ramipril', 'Atorvastatin', 'Furosemide', 'Spironolactone'],
    labs: {
      inr: 2.8,
      egfr: 62,
      k: 4.9,
      bnp: 450,
    },
    summary: '68M with AF on warfarin, heart failure, hypertension, diabetes, prior TIA.',
  },
  {
    id: 9,
    name: 'Patient 9',
    age: 55,
    sex: 'male',
    conditions: ['t2dm'],
    allergies: ['metoclopramide'],
    medications: ['Metformin', 'Empagliflozin', 'Insulin Glargine', 'Pregabalin', 'Duloxetine', 'Aspirin'],
    labs: {
      creatinine: 1.0,
      egfr: 72,
      hba1c: 7.8,
    },
    summary: '55M with diabetes, neuropathic pain treatment, dystonic reaction history.',
  },
  {
    id: 10,
    name: 'Patient 10',
    age: 10,
    sex: 'male',
    weightKg: 35,
    conditions: ['asthma'],
    allergies: ['aspirin'],
    medications: ['Salbutamol', 'Fluticasone', 'Montelukast'],
    labs: {
      fev1: '78%',
    },
    summary: '10yo with asthma and aspirin hypersensitivity.',
  },
];
