INSERT INTO public.patients (name, age, sex, weight_kg, conditions, allergies, medications, labs, summary) VALUES
('Patient 1', 65, 'male', NULL, '["t2dm"]', '["penicillin"]', '["Metformin", "Glimepiride", "Telmisartan", "Atorvastatin"]', '{"creatinine": 2.1, "egfr": 31.2, "hba1c": 8.4, "k": 5.1, "troponin": 4.8, "bp": "90/60", "hr": 110, "spo2": 94}', '65M with type 2 diabetes, CKD stage 3b, penicillin anaphylaxis.'),
('Patient 2', 58, 'female', NULL, '[]', '[]', '["Enoxaparin", "Paracetamol", "Tramadol", "Pantoprazole"]', '{"creatinine": 0.9, "egfr": 82, "hgb": 10.2}', '58F with pain control needs and mild anemia.'),
('Patient 3', 78, 'male', NULL, '["ckd", "hpn"]', '["sulfonamide"]', '["Amlodipine", "Telmisartan", "Metformin", "Glimepiride", "Atorvastatin", "Aspirin", "Pantoprazole", "Escitalopram", "Tamsulosin", "Paracetamol", "Diclofenac"]', '{"creatinine": 1.4, "egfr": 48, "k": 4.8}', '78M with polypharmacy, sulfonamide rash history, CKD stage 3a.'),
('Patient 4', 6, 'male', 20, '["epilepsy"]', '[]', '["Sodium Valproate", "Levetiracetam"]', '{"valproate_level": 85}', '6yo child with epilepsy on valproate and levetiracetam.'),
('Patient 5', 62, 'male', NULL, '["hf"]', '["ace inhibitor"]', '["Furosemide", "Carvedilol", "Amlodipine", "Erythropoietin", "Calcium"]', '{"creatinine": 4.8, "egfr": 12, "k": 5.6}', '62M with heart failure, advanced CKD, ACE inhibitor angioedema.');

INSERT INTO public.drugs (generic_name, generic_name_normalized, drug_class, renal_dosing) VALUES
('Metformin', 'metformin', 'biguanide', '{"rules": [{"maxEGR": 30, "action": "contraindicated", "message": "eGFR < 30: contraindicated"}]}'),
('Glimepiride', 'glimepiride', 'sulfonylurea', '{"rules": [{"maxEGR": 30, "action": "avoid", "message": "eGFR < 30: avoid"}]}'),
('Empagliflozin', 'empagliflozin', 'sglt2i', '{"rules": [{"maxEGR": 20, "action": "avoid", "message": "eGFR < 20: avoid"}]}'),
('Insulin Glargine', 'insulin glargine', 'insulin', '{"rules": [{"action": "monitor", "message": "Reduce insulin dose as eGFR declines"}]}'),
('Atorvastatin', 'atorvastatin', 'statin', '{"rules": [{"action": "none", "message": "No adjustment"}]}'),
('Rosuvastatin', 'rosuvastatin', 'statin', '{"rules": [{"maxEGR": 30, "action": "start_low", "message": "eGFR < 30: start low"}]}'),
('Amlodipine', 'amlodipine', 'ccb', '{"rules": [{"action": "none", "message": "No adjustment"}]}'),
('Telmisartan', 'telmisartan', 'arb', '{"rules": [{"action": "monitor", "message": "Monitor K+ in CKD"}]}'),
('Ramipril', 'ramipril', 'ace_inhibitor', '{"rules": [{"maxEGR": 30, "action": "reduce", "message": "eGFR < 30: reduce"}]}'),
('Lisinopril', 'lisinopril', 'ace_inhibitor', '{"rules": [{"maxEGR": 30, "action": "reduce", "message": "eGFR < 30: reduce"}]}'),
('Furosemide', 'furosemide', 'loop_diuretic', '{"rules": [{"action": "higher_dose", "message": "Higher doses may be required in CKD"}]}'),
('Spironolactone', 'spironolactone', 'k_sparing_diuretic', '{"rules": [{"maxEGR": 30, "action": "avoid", "message": "eGFR < 30: avoid"}]}'),
('Bisoprolol', 'bisoprolol', 'beta_blocker', '{"rules": [{"action": "none", "message": "No significant adjustment"}]}'),
('Carvedilol', 'carvedilol', 'beta_blocker', '{"rules": [{"action": "none", "message": "No adjustment"}]}'),
('Aspirin', 'aspirin', 'antiplatelet', '{"rules": [{"action": "none", "message": "No adjustment"}]}'),
('Clopidogrel', 'clopidogrel', 'antiplatelet', '{"rules": [{"action": "none", "message": "No adjustment"}]}'),
('Ticagrelor', 'ticagrelor', 'antiplatelet', '{"rules": [{"action": "none", "message": "No adjustment"}]}'),
('Warfarin', 'warfarin', 'vka', '{"rules": [{"action": "monitor", "message": "No adjustment; monitor INR"}]}'),
('Rivaroxaban', 'rivaroxaban', 'doac', '{"rules": [{"minEGR": 15, "maxEGR": 49, "action": "dose_adjust", "message": "eGFR 15-49: 15 mg daily"}, {"maxEGR": 15, "action": "avoid", "message": "eGFR < 15: avoid"}]}'),
('Apixaban', 'apixaban', 'doac', '{"rules": [{"maxEGR": 25, "action": "reduce", "message": "eGFR < 25: reduce"}]}'),
('Enoxaparin', 'enoxaparin', 'lmwh', '{"rules": [{"maxEGR": 30, "action": "once_daily", "message": "eGFR < 30: give once daily"}]}'),
('Amoxicillin', 'amoxicillin', 'penicillin', '{"rules": [{"maxEGR": 30, "action": "reduce_frequency", "message": "eGFR < 30: reduce frequency"}]}'),
('Amoxicillin-Clavulanate', 'amoxicillin-clavulanate', 'penicillin', '{"rules": [{"maxEGR": 30, "action": "reduce_frequency", "message": "eGFR < 30: reduce frequency"}]}'),
('Ampicillin', 'ampicillin', 'penicillin', '{"rules": [{"maxEGR": 30, "action": "reduce_frequency", "message": "eGFR < 30: reduce frequency"}]}'),
('Clarithromycin', 'clarithromycin', 'macrolide', '{"rules": [{"maxEGR": 30, "action": "reduce_50", "message": "eGFR < 30: reduce by 50%"}]}'),
('Azithromycin', 'azithromycin', 'macrolide', '{"rules": [{"action": "none", "message": "No adjustment"}]}'),
('Levofloxacin', 'levofloxacin', 'fluoroquinolone', '{"rules": [{"maxEGR": 50, "action": "adjust", "message": "eGFR < 50: adjust dose"}]}'),
('Ciprofloxacin', 'ciprofloxacin', 'fluoroquinolone', '{"rules": [{"maxEGR": 30, "action": "reduce_50", "message": "eGFR < 30: reduce by 50%"}]}'),
('Meropenem', 'meropenem', 'carbapenem', '{"rules": [{"maxEGR": 26, "action": "reduce", "message": "eGFR < 26: reduce dose"}]}'),
('Ceftriaxone', 'ceftriaxone', 'cephalosporin_3rd', '{"rules": [{"action": "none", "message": "No adjustment"}]}'),
('Cefazolin', 'cefazolin', 'cephalosporin_1st', '{"rules": [{"maxEGR": 35, "action": "reduce", "message": "eGFR < 35: reduce dose"}]}'),
('Nitrofurantoin', 'nitrofurantoin', 'nitrofuran', '{"rules": [{"maxEGR": 30, "action": "avoid", "message": "eGFR < 30: avoid"}]}'),
('Co-trimoxazole', 'co-trimoxazole', 'sulfonamide', '{"rules": [{"maxEGR": 15, "action": "avoid", "message": "eGFR < 15: avoid"}]}'),
('Gabapentin', 'gabapentin', 'gabapentinoid', '{"rules": [{"minEGR": 15, "maxEGR": 30, "action": "100mg_od", "message": "eGFR 15-30: dose 100 mg once daily"}, {"minEGR": 30, "maxEGR": 60, "action": "50pct", "message": "eGFR 30-60: give 50% of usual dose"}]}'),
('Pregabalin', 'pregabalin', 'gabapentinoid', '{"rules": [{"minEGR": 15, "maxEGR": 30, "action": "reduce_75", "message": "eGFR 15-30: 75% dose reduction"}, {"minEGR": 30, "maxEGR": 60, "action": "reduce", "message": "eGFR 30-60: reduce dose"}]}'),
('Escitalopram', 'escitalopram', 'ssri', '{"rules": [{"action": "none", "message": "No significant adjustment"}]}'),
('Fluoxetine', 'fluoxetine', 'ssri', '{"rules": [{"action": "none", "message": "No adjustment"}]}'),
('Duloxetine', 'duloxetine', 'snri', '{"rules": [{"maxEGR": 30, "action": "avoid", "message": "eGFR < 30: avoid"}]}'),
('Tramadol', 'tramadol', 'opioid', '{"rules": [{"maxEGR": 30, "action": "reduce", "message": "eGFR < 30: reduce dose"}]}'),
('Morphine', 'morphine', 'opioid', '{"rules": [{"maxEGR": 30, "action": "reduce", "message": "eGFR < 30: reduce dose due to metabolites"}]}'),
('Fentanyl', 'fentanyl', 'opioid', '{"rules": [{"action": "preferred", "message": "Preferred in CKD"}]}'),
('Paracetamol', 'paracetamol', 'analgesic', '{"rules": [{"action": "none", "message": "No adjustment"}]}'),
('Diclofenac', 'diclofenac', 'nsaid', '{"rules": [{"action": "avoid", "message": "Avoid in CKD"}]}'),
('Ibuprofen', 'ibuprofen', 'nsaid', '{"rules": [{"action": "avoid", "message": "Avoid in CKD"}]}'),
('Pantoprazole', 'pantoprazole', 'ppi', '{"rules": [{"action": "none", "message": "No adjustment"}]}'),
('Omeprazole', 'omeprazole', 'ppi', '{"rules": [{"action": "none", "message": "No adjustment"}]}'),
('Tamsulosin', 'tamsulosin', 'alpha_blocker', '{"rules": [{"action": "none", "message": "No adjustment"}]}'),
('Digoxin', 'digoxin', 'cardiac_glycoside', '{"rules": [{"maxEGR": 30, "action": "reduce", "message": "eGFR < 30: reduce and monitor levels"}]}'),
('Phenytoin', 'phenytoin', 'anticonvulsant', '{"rules": [{"action": "complex", "message": "Complex dosing in CKD"}]}'),
('Sodium Valproate', 'sodium valproate', 'anticonvulsant', '{"rules": [{"action": "none", "message": "No significant adjustment"}]}'),
('Amiodarone', 'amiodarone', 'antiarrhythmic', '{"rules": [{"action": "monitor", "message": "Monitor cardiac and renal function"}]}'),
('Simvastatin', 'simvastatin', 'statin', '{"rules": [{"action": "none", "message": "No adjustment"}]}'),
('Methotrexate', 'methotrexate', 'antimetabolite', '{"rules": [{"action": "monitor", "message": "Renal clearance and cytopenia monitoring"}]}'),
('Carbamazepine', 'carbamazepine', 'anticonvulsant', '{"rules": [{"action": "monitor", "message": "Complex hepatic metabolism"}]}'),
('Theophylline', 'theophylline', 'bronchodilator', '{"rules": [{"action": "monitor", "message": "Therapeutic drug monitoring recommended"}]}'),
('Ondansetron', 'ondansetron', 'antiemetic', '{"rules": [{"action": "none", "message": "No adjustment"}]}'),
('Lithium', 'lithium', 'mood_stabilizer', '{"rules": [{"action": "monitor", "message": "Serum level monitoring required in CKD"}]}'),
('Contrast dye', 'contrast dye', 'contrast_dye', '{"rules": [{"action": "avoid", "message": "Avoid in significant CKD"}]}');

INSERT INTO public.drug_interactions (drug_a_id, drug_b_id, severity, mechanism, clinical_effect, management) VALUES
((SELECT id FROM public.drugs WHERE generic_name = 'Clarithromycin'), (SELECT id FROM public.drugs WHERE generic_name = 'Atorvastatin'), 'SEVERE', 'CYP3A4 inhibition', '4-5x statin levels → rhabdomyolysis', 'Avoid clarithromycin or use azithromycin'),
((SELECT id FROM public.drugs WHERE generic_name = 'Clarithromycin'), (SELECT id FROM public.drugs WHERE generic_name = 'Rosuvastatin'), 'MODERATE', 'Weak CYP3A4 interaction', 'Increased myopathy risk', 'Monitor for muscle pain'),
((SELECT id FROM public.drugs WHERE generic_name = 'Clarithromycin'), (SELECT id FROM public.drugs WHERE generic_name = 'Amlodipine'), 'MODERATE', 'CYP3A4 inhibition', 'Hypotension risk', 'Monitor blood pressure'),
((SELECT id FROM public.drugs WHERE generic_name = 'Clarithromycin'), (SELECT id FROM public.drugs WHERE generic_name = 'Warfarin'), 'SEVERE', 'CYP interaction', 'Increased INR → bleeding', 'Monitor INR closely'),
((SELECT id FROM public.drugs WHERE generic_name = 'Ciprofloxacin'), (SELECT id FROM public.drugs WHERE generic_name = 'Warfarin'), 'MODERATE', 'CYP1A2 inhibition', 'Increased INR', 'Monitor INR'),
((SELECT id FROM public.drugs WHERE generic_name = 'Fluoxetine'), (SELECT id FROM public.drugs WHERE generic_name = 'Tramadol'), 'SEVERE', 'Serotonin syndrome', 'Life-threatening serotonin syndrome', 'Avoid combination'),
((SELECT id FROM public.drugs WHERE generic_name = 'Escitalopram'), (SELECT id FROM public.drugs WHERE generic_name = 'Tramadol'), 'MODERATE', 'Serotonin risk', 'Monitor for serotonin syndrome', 'Use caution'),
((SELECT id FROM public.drugs WHERE generic_name = 'Diclofenac'), (SELECT id FROM public.drugs WHERE generic_name = 'Telmisartan'), 'SEVERE', 'Nephrotoxicity', 'Triple whammy with renal injury', 'Avoid together if possible'),
((SELECT id FROM public.drugs WHERE generic_name = 'Diclofenac'), (SELECT id FROM public.drugs WHERE generic_name = 'Ramipril'), 'SEVERE', 'Nephrotoxicity', 'Triple whammy with renal injury', 'Avoid together if possible'),
((SELECT id FROM public.drugs WHERE generic_name = 'Ibuprofen'), (SELECT id FROM public.drugs WHERE generic_name = 'Aspirin'), 'MODERATE', 'Reduced antiplatelet efficacy', 'Reduced protection against clotting', 'Avoid routine combination'),
((SELECT id FROM public.drugs WHERE generic_name = 'Warfarin'), (SELECT id FROM public.drugs WHERE generic_name = 'Aspirin'), 'SEVERE', 'Additive bleeding risk', 'Major hemorrhage', 'Avoid unless strict indication and monitoring'),
((SELECT id FROM public.drugs WHERE generic_name = 'Spironolactone'), (SELECT id FROM public.drugs WHERE generic_name = 'Ramipril'), 'MODERATE', 'Hyperkalemia', 'Cardiac arrest risk', 'Monitor potassium closely'),
((SELECT id FROM public.drugs WHERE generic_name = 'Spironolactone'), (SELECT id FROM public.drugs WHERE generic_name = 'Telmisartan'), 'MODERATE', 'Hyperkalemia', 'High potassium risk', 'Monitor potassium levels'),
((SELECT id FROM public.drugs WHERE generic_name = 'Digoxin'), (SELECT id FROM public.drugs WHERE generic_name = 'Amiodarone'), 'SEVERE', 'Reduced clearance', 'Digoxin toxicity', 'Reduce digoxin dose and monitor levels'),
((SELECT id FROM public.drugs WHERE generic_name = 'Metformin'), (SELECT id FROM public.drugs WHERE generic_name = 'Contrast dye'), 'MODERATE', 'Lactic acidosis risk', 'Contrast exposure elevates risk', 'Hold metformin around contrast'),
((SELECT id FROM public.drugs WHERE generic_name = 'Phenytoin'), (SELECT id FROM public.drugs WHERE generic_name = 'Sodium Valproate'), 'MODERATE', 'Altered metabolism', 'Variable phenytoin levels', 'Monitor drug levels'),
((SELECT id FROM public.drugs WHERE generic_name = 'Duloxetine'), (SELECT id FROM public.drugs WHERE generic_name = 'Tramadol'), 'SEVERE', 'Serotonin syndrome', 'Life-threatening serotonin syndrome', 'Avoid this combination'),
((SELECT id FROM public.drugs WHERE generic_name = 'Clopidogrel'), (SELECT id FROM public.drugs WHERE generic_name = 'Omeprazole'), 'MODERATE', 'CYP2C19 inhibition', 'Reduced antiplatelet effect', 'Use alternative PPI if possible'),
((SELECT id FROM public.drugs WHERE generic_name = 'Clopidogrel'), (SELECT id FROM public.drugs WHERE generic_name = 'Pantoprazole'), 'MINOR', 'Weak CYP2C19 effect', 'Possible reduced antiplatelet effect', 'Pantoprazole preferred over omeprazole'),
((SELECT id FROM public.drugs WHERE generic_name = 'Rivaroxaban'), (SELECT id FROM public.drugs WHERE generic_name = 'Clarithromycin'), 'SEVERE', 'P-gp and CYP3A4 inhibition', 'Increased bleeding risk', 'Avoid together or change agent'),
((SELECT id FROM public.drugs WHERE generic_name = 'Apixaban'), (SELECT id FROM public.drugs WHERE generic_name = 'Clarithromycin'), 'MODERATE', 'P-gp and CYP3A4 inhibition', 'Increased anticoagulant levels', 'Use caution or choose alternative'),
((SELECT id FROM public.drugs WHERE generic_name = 'Simvastatin'), (SELECT id FROM public.drugs WHERE generic_name = 'Amlodipine'), 'MODERATE', 'CYP3A4 inhibition', 'Limit simvastatin to 20 mg', 'Reduce simvastatin dose'),
((SELECT id FROM public.drugs WHERE generic_name = 'Methotrexate'), (SELECT id FROM public.drugs WHERE generic_name = 'Co-trimoxazole'), 'SEVERE', 'Antifolate interaction', 'Pancytopenia', 'Avoid combination'),
((SELECT id FROM public.drugs WHERE generic_name = 'Carbamazepine'), (SELECT id FROM public.drugs WHERE generic_name = 'Clarithromycin'), 'SEVERE', 'CYP3A4 inhibition', 'Carbamazepine toxicity', 'Avoid combination'),
((SELECT id FROM public.drugs WHERE generic_name = 'Theophylline'), (SELECT id FROM public.drugs WHERE generic_name = 'Ciprofloxacin'), 'SEVERE', 'CYP1A2 inhibition', 'Seizures', 'Avoid together'),
((SELECT id FROM public.drugs WHERE generic_name = 'Escitalopram'), (SELECT id FROM public.drugs WHERE generic_name = 'Ondansetron'), 'MODERATE', 'QT prolongation', 'Torsades risk', 'Use caution'),
((SELECT id FROM public.drugs WHERE generic_name = 'Metformin'), (SELECT id FROM public.drugs WHERE generic_name = 'Furosemide'), 'MINOR', 'Lactic acidosis risk in CKD', 'Small added risk', 'Monitor renal function'),
((SELECT id FROM public.drugs WHERE generic_name = 'Morphine'), (SELECT id FROM public.drugs WHERE generic_name = 'Escitalopram'), 'MINOR', 'CNS depression', 'Increased sedation', 'Monitor consciousness'),
((SELECT id FROM public.drugs WHERE generic_name = 'Pregabalin'), (SELECT id FROM public.drugs WHERE generic_name = 'Morphine'), 'MODERATE', 'CNS and respiratory depression', 'Sedation and respiratory depression', 'Reduce doses and monitor');

INSERT INTO public.allergy_cross_reactivity (drug_class_a, drug_class_b, cross_reactivity_pct, clinical_guidance) VALUES
('penicillin', 'penicillin', 100, 'Same class — direct match'),
('penicillin', 'cephalosporin_1st', 1.5, 'Avoid if anaphylaxis'),
('penicillin', 'cephalosporin_3rd', 0.5, 'Use with caution'),
('penicillin', 'carbapenem', 1, 'Generally safe'),
('sulfonamide', 'sulfonamide', 100, 'Same class'),
('ace_inhibitor', 'ace_inhibitor', 100, 'Angioedema risk'),
('ace_inhibitor', 'arb', 0, 'ARBs are safe'),
('nsaid', 'nsaid', 50, 'Avoid all NSAIDs in aspirin-exacerbated reactions');